apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafe-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cafe-ui
  template:
    metadata:
      labels:
        app: cafe-ui
    spec:
      containers:
      - name: cafe-ui
<<<<<<< HEAD
        image: premrepal/cafe-ui:31
=======
        image: premrepal/cafe-ui:30
        imagePullPolicy: Always
>>>>>>> 4d20f43 (fixed image policy)
        ports:
        - containerPort: 80


